### ISSUE TITLE
VM disk images are not encrypted

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#101]
**Is your feature request related to a problem? Please describe.**
In the Azure portal, I see that the Linux VM I have created via Guacamole does not have disk encryption enabled. It almost certainly should have it enabled, for all VMs

**Describe the solution you'd like**
We need to check that encryption is enabled for both Linux and Windows VMs created via Guacamole, plus for any other VMs created by the TRE - e.g. for Azure ML, Gitea, the Resource Processor...

**Comment by akolensky** [comment]
Pull request created - atm the keys are managed automatically by the platform but can be adjusted to manual management with custom keys deployed in key vault if necessary for compliance.

#124
