### ISSUE TITLE
Ubuntu version number is hardwired into Nexus configuration

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#102]
**Describe the bug**
in `templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/apt_sources_config.yml`, the version number `18.04` is hardwired. This needs to be dependent on the actual version the VM boots with.

**Comment by akolensky** [comment]
Configure it to be the latest stable version for now

**Comment by akolensky** [comment]
Version hard coded to 22.04 atm
