### ISSUE TITLE
Test enabling boot diagnostics for Guacamole VMs

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#103]
**Is your feature request related to a problem? Please describe.**
At least for Linux VMs, console access requires that boot diagnostics be enabled. This can be done in Terraform, but requires a storage account to store the diagnostics in. The storage account should be per-workspace, in the guacamole configuration, and the Linux VMs should use it by default.

**Comment by akolensky** [comment]
Tested out creating storage account per workspace and assigning it to boot_diagnostics per Linux VM.
Do we need also CLI logs too?
