### ISSUE TITLE
Disable malware scanning

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#118]
This is relates to #117, about the size of files in the airlock import/export process. Files are currently scanned by Defender for Cloud, which has a [hard limit of 2 GB for the file size](https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-malware-scan#malware-scanning-in-defender-for-storage-helps-protect-storage-accounts-from-malicious-content). Files larger than that are automatically failed, so we need to disable Defender for Cloud.

The choice of scanning for malware or not is made at the TRE config level, so it's possible this will result in a significant rebuild of components, depending on how the terraform code responds to a changed configuration variable (`enable_airlock_malware_scanning`) when it comes to updating stuff. Need to experiment before going live!

@akolensky, let's discuss this and see how best to test it.

**Comment by akolensky** [comment]
Need to validate it throught config file flag too

**Comment by TonyWildish-BH** [comment]
After discussion with Steven, we're keeping the malware scanning, and living with the 2 GB limit. If anyone wants a bigger file than that, they'll have to split it. If it's _much_ bigger, they should probably be getting it through a different channel, such as the Data Core.

So, closing this ticket.
