### ISSUE TITLE
Create Custom VM User Persona and relevant attributes

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#133]
Need to create the user persona for a user responsobile for managing Custom VM Templates

**Comment by TonyWildish-BH** [comment]
Can you expand on this, please. Why is a persona needed, and what should it do?

**Comment by akolensky** [comment]
I beleive this was about creating a persona similar to Airlock Reviewer but more related to capability of managing the Custom VMs? Although I do not recall exactly how it came up to existence. It was after our call about all the other user roles that exist on TRE at present.

**Comment by TonyWildish-BH** [comment]
OK, that's something we can manage outside the SDE, I think, so I'll close this ticket.
