### ISSUE TITLE
Simplifying adding users to the SDE

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#138]
As described in https://github.com/Barts-Life-Science/AzureTRE/wiki/For-SDE-Administrators#user-management, the process for adding users is currently rather clunky and manual. This should be possible to script, then eventually, after connection to the DP, to automate.

**Describe the solution you'd like**
A script, taking the workspace ID, the user name, and the role they should be granted. That's enough for a first step, we can build on that.

Can be written in PowerShell initially, to get the commands right, but may eventually need to migrate to Python, so it can be integrated into other tooling. Not sure...

N.B. There are other options besides the way it's currently done. One of the options when creating a workspace is to "Create AAD Groups for each workspace role", which should be investigated first to see if it simplifies the process.

**Comment by BIOKU-BH** [comment]
Thanks Tony. I will pick this up and see what solution I can come up with solve this.
