### ISSUE TITLE
MFA bypass due to misconfiguration

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#176]
The penetration testing report showed that (page 27):

The Entra ID tenancy required users to enroll into Multi-Factor Authentication (MFA). However, due to a misconfiguration, an attacker with a valid credential, could authenticate to the Microsoft Graph API without an MFA challenge. This service can be used to generate tokens to access additional services, resulting in complete compromise of confidentiality and integrity of the account.

Upon providing a correct credential to an Entra ID account, it was observed that the user was required by Microsoft to verify the authenticity of the login via MFA. By requiring users to respond to challenges when attempting to authenticate to their account, it improves the integrity of the authentication attempt and helps mitigate against common compromise scenarios, where poor password choice has been followed, or users have become susceptible to phishing.

This is a medium level risk, but is something we must fix before the next pen-test.

**Comment by TonyWildish-BH** [comment]
Bioku, following up on this, I have two comments:
1. [In the documentation](https://github.com/Barts-Life-Science/AzureTRE/wiki/z-Investigation-of-MFA-bypass-using-Microsoft-Graph-API.), the screenshot is illegibly small, I can't read the text well enough to see what it's saying.
2. Is there a conclusion you can draw, so I don't have to work it out myself? It's not clear to me if the issue is accepted as-is, is resolved, or what the conclusion is.

**Comment by BIOKU-BH** [comment]
Hello Tony, I have now updated the screenshot and I am hopeful it comes out better on your end. Should it not come out better, here is the link to the page on Azure: [https://portal.azure.com/#view/Microsoft_AAD_ConditionalAccess/PolicyBlade](url)

I have also added a conclusion and recommendation based on the findings.

**Comment by TonyWildish-BH** [comment]
perfect, thanks!
