### ISSUE TITLE
Windows: SMB Signing Disabled

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#186]
The penetration testing report showed that (page 59):

The Windows VMs were not configured to authenticate SMB requests. An attacker can abuse this misconfiguration in scenarios where they have been able to manipulate the victim’s traffic, enabling them to impersonate the victim. This can lead to an attacker obtaining a foothold on a system under the correct conditions.

Server Message Block (SMB) signing allows a machine to confirm the authenticity of SMB packets and helps to prevent person-in-the-middle attacks. The absence of SMB signing could lead to SMB relay attacks and result in code execution on target systems, though this requires the attacker to successfully relay a credential where the user is local administrator on the system. Irrespective of whether the victim is granted privileges, an attacker can abuse the feature to capture credentials, or perform enumeration of the Active Directory domain.

The following configuration was observed for the SMB server service on the system, which had SMB signing disabled:
`HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\RequireSecuritySignature, Value: 0`

This is a medium level risk, but is something we must fix before the next pen-test.

**Comment by TonyWildish-BH** [comment]
Bioku, can you confirm if this fix is now baked into the custom images?

**Comment by BIOKU-BH** [comment]
Hello Tony, Yes, this is now available in the custom images in the development environment.
