### ISSUE TITLE
Investigate - What does deleting a project workspace do?

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#22]
## Description

When I delete a project workspace, how far does that cleanup go?

Specifically, does it remove the app registrations for that workspace? Does it delete locked resources, if any? Are there any RBAC / IAM roles created that also need to be deleted?

**Comment by akolensky** [comment]
It appears by running the project deletion from the TRE portal will delete everything but the application registries.
