### ISSUE TITLE
Add functionality to push a file with user credentials for shared services such as Gitea and Nexus

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#54]
At the moment only Gitea admin account can be used to add commits to the Gitea repo.

Need more user created to be able track changes done by multiple users collaborating on the single repo.

**Comment by TonyWildish-BH** [comment]
@akolensky, the title and the description of this ticket don't line up. There are two separate issues we need to address:
1. Making Gitea more user-friendly, by mapping user accounts into it. This is related to mapping the user IDs into the workspace.
2. Pushing credentials/secrets for all services into the workspace where they can be picked up easily. This needs some planning, we need the Workspace Admin to be able to pull a fresh set of credentials in case a) someone new joins the project, b) Gitea gets re-deployed, c) MySQL gets deployed, etc. This means the key vault has to be exposed to the Workspace Admin somehow, maybe through a button in the UI, maybe through a service account in the workspace...
