### ISSUE TITLE
How does sharing work between multiple machines in the same project/

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#61]
Investigate the interaction of VMs through the shared storage account:
Actions:
- Create new files
- Update an existing file

OS Combos:
- Linux -> Linux
- Linux -> Windows
- Windows -> Windows
- Windows -> Linux

Spike write up can be found here: [Azure Shared File Storage Spike](https://github.com/Barts-Life-Science/AzureTRE-docs/blob/main/development-spikes/vm-shared-storage.md)

**Comment by TonyWildish-BH** [comment]
Thanks Andrii,

please also test how well the filesystems reconnect after their automounts time out (e.g. overnight). For extra points, maybe look into replacing the automounter with a permanent mount, see if that looks feasible.
