### ISSUE TITLE
Disable the thinlcient_drive on the Linux and Windows VMs

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#63]
At present the XRDP on Linux VMs create a thinclient_drive by default. 
It can be misleading to the users who wish to use it potentially as shared drive, and given there is local storage on the VM and shared-storage mounted from Azure, we may not need the drive entirely.

For more info, similar issue was raised externally for similar reasons: https://github.com/neutrinolabs/xrdp/issues/1283

![image](https://github.com/Barts-Life-Science/AzureTRE/assets/125355163/60af6c35-d48e-4aad-ba8c-07cf7d8acb2e)

**Comment by TonyWildish-BH** [comment]
I don't yet know how to disable the mount, but I found by chance that the path to it is set in `/etc/xrdp/sesman.ini`.

**Comment by akolensky** [comment]
At the moment drive does not cause issues or deter any development. It stays
