### ISSUE TITLE
Windows VMs shared storage doesn't mount if the Access Key gets "/" at start of the key

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#69]
**Describe the bug**
During the Windows VM deployment it runs `net use` in [vm config](https://github.com/Barts-Life-Science/AzureTRE/blob/main/templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/vm_config.ps1) to mount the storage file share as a Z drive. 

The command depends on the storage access keys. If the storage access keys start with a "/" it will fail to mount because Powershell considers it as an operand option. Rotating the key doesn't work to resolve the process for future deployed VMs, because the VM image teplate needs to be updated too.

**Steps to reproduce**

1. Deploy the Windows VM (any image)
1. Start the VM and go to File Explorer
1. No location is present

**Azure TRE release version (e.g. v0.14.0 or main):**
API Version - 0.18.5

**Deployed Azure TRE components - click the (i) in the UI:**
Cosmos DB OK
Service Bus OK
Resource Processor OK

**Comment by TonyWildish-BH** [comment]
There's a [ticket with MS about this](https://github.com/microsoft/AzureTRE/issues/3967), which they haven't replied to yet. Let's see what they say before we do anything concrete.
